In [1]:
import numpy as np

In [2]:
# 随机生成(0,1)均匀分布的数据
a = np.random.rand(5)
print(a)

[0.81629276 0.18376025 0.65828163 0.46493736 0.85091191]


In [3]:
a = np.random.rand(2, 3)
print(a)

[[0.98717091 0.53018817 0.0510147 ]
 [0.05188794 0.79137123 0.52654051]]


In [6]:
# 随机生成均匀分布的整数
b = np.random.randint(0, 100, size=[2,3])
print(b)

[[58 19 60]
 [53 48 24]]


In [7]:
# 随机生成服从标准正态分布的数据
c = np.random.randn(2, 5)
print(c)

[[ 0.55139594 -0.72406339  0.56904278  0.7618092  -1.09439723]
 [-0.05243343  1.10069409  0.15954578  1.0441573  -0.0201726 ]]


In [8]:
print( (c+5) * 10)

[[55.5139594  42.75936609 55.69042781 57.61809204 39.05602772]
 [49.47566568 61.00694092 51.59545779 60.44157296 49.798274  ]]
