In [1]:
from sklearn.preprocessing import MinMaxScaler

In [2]:
X = [[2, 1], [3, 1], [1, 4], [2, 6]]

In [3]:
# 定义归一化类的对象
scaler = MinMaxScaler(feature_range=(-1, 1))
# 将缩放器应用到特征上
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[ 0.  -1. ]
 [ 1.  -1. ]
 [-1.   0.2]
 [ 0.   1. ]]


In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
print(X)

[[2, 1], [3, 1], [1, 4], [2, 6]]


In [6]:
# 标准化
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[ 0.         -0.94280904]
 [ 1.41421356 -0.94280904]
 [-1.41421356  0.47140452]
 [ 0.          1.41421356]]


In [7]:
import numpy as np

In [8]:
X = np.array(X)
print(X)

[[2 1]
 [3 1]
 [1 4]
 [2 6]]


In [9]:
mean = np.mean(X, axis=0)
print(mean)

[2. 3.]


In [10]:
std = np.std(X, axis=0)
print(std)

[0.70710678 2.12132034]


In [11]:
print((X - mean) / std)

[[ 0.         -0.94280904]
 [ 1.41421356 -0.94280904]
 [-1.41421356  0.47140452]
 [ 0.          1.41421356]]
