In [1]:
import numpy as np

In [2]:
A = np.array([[1, 1], [2, 2], [0, 0]])

U, S, V = np.linalg.svd(A)

print(U)
print(S)
print(V)

[[-0.4472136  -0.89442719  0.        ]
 [-0.89442719  0.4472136   0.        ]
 [ 0.          0.          1.        ]]
[3.16227766e+00 8.22677308e-17]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [3]:
from sklearn.utils.extmath import randomized_svd

In [4]:
U, S, V = randomized_svd(A, n_components=2)
print(U)
print(S)
print(V)

[[ 0.4472136   0.89442719]
 [ 0.89442719 -0.4472136 ]
 [ 0.         -0.        ]]
[3.16227766e+00 1.62596948e-32]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [5]:
from sklearn.decomposition import PCA

In [6]:
X = np.random.randn(100, 3)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
print(X_pca.shape)

(100, 2)
